services:
  appgranjapi:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 8080
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: 4dM1N.2024**
      DATABASE_NAME: granjadb
      HOST_DATABASE: localhost
      PORT_DATABASE: 3806
      WOMPI_PLUBIC_KEY: "public_key"
      WOMPI_PRIVATE_KEY: "private_key"
      WOMPI_EVENT_SECRET: "prod_events"
      WOMPI_INTEGRITY_SECRET: "prod_integrity"
      WOMPI_RETRIES: 5
    ports:
      - 8080:8080
    networks:
      bot_net:
        aliases:
          - backend_granja_api
networks:
  bot_net:
    name: bot_network
    driver: bridge
    ipam:
      driver: default
