server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: app-granja-api
  datasource:
    username: root
    password: 4dM1N.2025**
    url: jdbc:mariadb://localhost:3806/granjadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
---
server:
  port: ${PORT}
  servlet:
    context-path: /api
spring:
  config:
    activate:
      on-profile: release
  application:
    name: app-granja-api    
  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: jdbc:mariadb://${HOST_DATABASE}:${PORT_DATABASE}/${DATABASE_NAME}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false